### ISSUE TITLE
download couple of songs from soundcloud

### ISSUE THREAD

**Issue by 8lendzior** [89z/mech#17]
I'm sorry for stupid question, but how am I supposed to use it? I can't find any information about it, I'm a newbie.

**Comment by 89z** [comment]
please explain what you wish to do

**Comment by 8lendzior** [comment]
> Do you want to use the API, or do you just want to use a tool?

Just want to use a tool, just want to download the song.

**Comment by 89z** [comment]
OK I used to have a tool for this, let me finish lunch and I will find it in the history

**Comment by 89z** [comment]
Can you please provide example URL? Also if youre on Windows, I can make a build for you - otherwise you will need to build yourself

**Comment by 8lendzior** [comment]
> Can you please provide example URL? Also if youre on Windows, I can make a build for you - otherwise you will need to build yourself

URL - https://soundcloud.com/kino-scmusic/mqymd53jtwag?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing
I use linux.

**Comment by 89z** [comment]
Are you able to build yourself? I have instruction here:

https://github.com/89z/mech#how-to-install

**Comment by 8lendzior** [comment]
I mean I don't know if I understand this correctly but I have it installed. I installed it by using yay (the aur helper).

**Comment by 89z** [comment]
So is it working? Can you download SoundCloud?

**Comment by 8lendzior** [comment]
I mean the problem is that I don't know what command should I use.

**Comment by 89z** [comment]
To get help, just run `soundcloud` or `soundcloud -h`:

~~~
Usage of C:\Users\Steven\go\bin\soundcloud.exe:
  -a string
        address
  -i    info only
~~~

Based on that, you can download like this:

~~~
soundcloud -a https://soundcloud.com/kino-scmusic/mqymd53jtwag
~~~

**Comment by 8lendzior** [comment]
That's exactly what I was looking for! Thank you very much!

**Comment by 89z** [comment]
I added a small instruction to the command folder:

https://github.com/89z/mech/tree/master/cmd/soundcloud

**Comment by 8lendzior** [comment]
One more small question. Is it possible to download all the song of the artist with a single command?

**Comment by 89z** [comment]
please provide example URL

**Comment by 89z** [comment]
Its not possible right now, but I will see if I can implement it

**Comment by 8lendzior** [comment]
Not a problem, I was just curious. Thank you very much once again!

**Comment by 89z** [comment]
Program should support both of these now:

- https://soundcloud.com/kino-scmusic/mqymd53jtwag
- https://soundcloud.com/kino-scmusic

Note that for users, current implementation is limited to 999 tracks. I might change that in the future if need arises.
