### ISSUE TITLE
Instagram: an audio stream is separated from video

### ISSUE THREAD

**Issue by Sonotoki-da** [89z/mech#20]
I couldn't figure out how one audio file is connected to the corresponding video file. Well, it's okay when there's only one video in a post, I can just merge them with ffmpeg without a doubt.

**Comment by 89z** [comment]
please provide example URL

**Comment by Sonotoki-da** [comment]
Um, please wait, I'll just make one :') I just thought the possibility of that kind of posts to be exist

**Comment by 89z** [comment]
Sorry, I dont think this is a good use of my time. I like to deal with real problems, not invented ones.

If you can find a public post, thats not your own, that demonstrates the problem, I will reopen and fix the issue. Thanks.
