### ISSUE TITLE
[Youtube] Very slow download 

### ISSUE THREAD

**Issue by 89z** [89z/mech#23]
https://www.youtube.com/watch?v=qqiC88f9ogU

**Comment by 89z** [comment]
Fixed:

~~~
PS C:\> youtube.exe -b qqiC88f9ogU
POST https://www.youtube.com/youtubei/v1/player
Status: OK
GET https://rr2---sn-q4flrney.googlevideo.com/videoplayback?expire=1648250574&ei=bvo9Yv67KvOvlu8P_MmS8AQ&ip=72.181.23.38&id=o-AKW9f9LqpzCE414cQ_g6Bx_16WAy-9c_x5WI1lD7A7uM&itag=398&source=youtube&requiressl=yes&mh=xo&mm=31%2C26&mn=sn-q4flrney%2Csn-a5mlrnek&ms=au%2Conr&mv=m&mvi=2&pl=16&initcwndbps=1441250&vprv=1&mime=video%2Fmp4&gir=yes&clen=23197580&dur=154.999&lmt=1646445661380222&mt=1648228625&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAIM_KWIHhHAZjhO_pk2po9zHbJ6UEWPbKe92oayvpkAsAiEA1pQP2iFpAn0RFWvGvosdxoVLeTWoTEmNZEJ5DbQH7MA%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgQ1DCXlTAE1I5e7EnaxEiDsV7JzIEotW766mtUXNM1pACIQDAUHyLTEsvmSjzAx6myisf96Xrtp2hX8pmDrGIuMSeOw%3D%3D
43.1%   10.000 MB       7.086 MB/s
86.2%   20.000 MB       7.521 MB/s
GET https://rr2---sn-q4flrney.googlevideo.com/videoplayback?expire=1648250574&ei=bvo9Yv67KvOvlu8P_MmS8AQ&ip=72.181.23.38&id=o-AKW9f9LqpzCE414cQ_g6Bx_16WAy-9c_x5WI1lD7A7uM&itag=251&source=youtube&requiressl=yes&mh=xo&mm=31%2C26&mn=sn-q4flrney%2Csn-a5mlrnek&ms=au%2Conr&mv=m&mvi=2&pl=16&initcwndbps=1441250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=2348726&dur=155.021&lmt=1646413485218097&mt=1648228625&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJ5haYvZbPfOwS14_0VpAOLxxpyZeOi9sC0WMx6toKw4CIHW6Ut4twNdWBrBPTnPodKj0QRMRCheAloj1yl75UG8l&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgQ1DCXlTAE1I5e7EnaxEiDsV7JzIEotW766mtUXNM1pACIQDAUHyLTEsvmSjzAx6myisf96Xrtp2hX8pmDrGIuMSeOw%3D%3D
~~~

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30715

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30752

**Comment by 89z** [comment]
@1vanK

**Comment by optionsx** [comment]
ytdl-core is very fast at downloading it, and it's open-source!

**Comment by 89z** [comment]
https://github.com/kkdai/youtube/issues/232

**Comment by Clashkid155** [comment]
Hey, you mentioned you fixed this on `youtube` plugin. I can't seem to find how or the commit.

**Comment by 89z** [comment]
Current workaround is using the ANDROID client:

https://github.com/89z/mech/blob/v1.51.3/youtube/client.go#L16-L20

however I also discovered that even with other clients, you can run 16 or more connections for better speed. I am still working on that solution.

**Comment by Clashkid155** [comment]
So for now i can just change the client id on the `YouTube` plugin to what ever is here? I would've used your youtube library but i need go1.18 which is not available to me now

**Comment by 89z** [comment]
> So for now i can just change the client id on the `YouTube` plugin to what ever is here?

If you are asking about YouTube-DL, sorry I cant help with that.

> I would've used your YouTube library but i need go1.18 which is not available to me now.

Can you explain why you cant use Go 1.18? I am willing to downgrade the module to Go 1.17, but I need a good reason, as it was a helpful update.

> Isn't 16 connection a bit much?

The throttle speed is 50 kB/s, so even with 16 connections, that only 800 kB/s. Ideally I would like to use even more, but I have to do more testing.

**Comment by Clashkid155** [comment]
> If you are asking about YouTube-DL, sorry I cant help with that.
Nope. I'm talking about [kkdai/youtube](https://github.com/kkdai/youtube)

> Can you explain why you cant use Go 1.18? I am willing to downgrade the module to Go 1.17, but I need a good reason, as it was a helpful update.

Well, it's not really in my distribution(Linux) repo. There's no need to downgrade the package as I'll, hopefully get it soon.

> The throttle speed is 50 kB/s, so even with 16 connections, that only 800 kB/s. Ideally I would like to use even more, but I have to do more testing.

Oh. I get it now.

**Comment by 89z** [comment]
> Nope. I'm talking about [kkdai/youtube](https://github.com/kkdai/youtube)

Looks like its here:

https://github.com/kkdai/youtube/blob/35992589/client.go#L126-L131

> Well, it's not really in my distribution(Linux) repo. There's no need to downgrade the package as I'll, hopefully get it soon.

what distro is it? I know that Alpine has it already.

**Comment by Clashkid155** [comment]
> Looks like its here:
> https://github.com/kkdai/youtube/blob/35992589/client.go#L126-L131

Thanks for this!!

> what distro is it? I know that Alpine has it already.

Manjaro. Since they hold back update for some time, i haven't gotten the 1.18 update but hoping it arrives this week. I could get the update from the aur but i don't want to do that.

**Comment by 89z** [comment]
I just remembered, you can get Linux version here:

https://go.dev/dl

its already built, you just have to extract it. Are you avoiding that for some reason?

**Comment by Clashkid155** [comment]
Ya. I'm waiting for Manjaro to drop it plus it's only your library that needs it so i can wait.
Thanks for the information.
