### ISSUE TITLE
PBS Nova

### ISSUE THREAD

**Issue by 89z** [89z/mech#38]
https://www.pbs.org/wgbh/nova/video/nova-universe-revealed-milky-way/

`github.com/yt-dlp/yt-dlp/issues/1643`

**Comment by 89z** [comment]
Fixed:

~~~
PS C:\> pbs -i -a https://www.pbs.org/wgbh/nova/video/nova-universe-revealed-milky-way/
GET https://www.pbs.org/wgbh/nova/video/nova-universe-revealed-milky-way/
GET https://player.pbs.org/partnerplayer/wwGgFRSNeKGrsgjdYh6efQ==/?topbar=false&end=0&endscreen=true&start=0&autoplay=false
GET https://urs.pbs.org/redirect/573a58f8dec844e8b7d1978109ffc356/
nova-universe-revealed-milky-way-4io957
Resolution:1280x720 Bandwidth:5499849 Codecs:avc1.64001f,mp4a.40.2
Resolution:1280x720 Bandwidth:3759707 Codecs:avc1.64001f,mp4a.40.2
Resolution:1920x1080 Bandwidth:8009771 Codecs:avc1.640028,mp4a.40.2
Resolution:960x540 Bandwidth:2587508 Codecs:avc1.64001f,mp4a.40.2
Resolution:768x432 Bandwidth:1510468 Codecs:avc1.64001e,mp4a.40.2
Resolution:640x360 Bandwidth:1075996 Codecs:avc1.64001e,mp4a.40.2
Resolution:480x270 Bandwidth:622742 Codecs:avc1.4d4015,mp4a.40.2
Resolution:416x234 Bandwidth:355798 Codecs:avc1.4d400c,mp4a.40.2
~~~

**Comment by 89z** [comment]
@Mennaruuk

**Comment by wxolp** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1643

**Comment by Mennaruuk** [comment]
@89z thanks for the heads up and fix, I’m compiling today, can’t wait!!

**Comment by 89z** [comment]
I just got this working today, so I made a few tweaks since the last commit:

- Lowered the default target bandwidth. Of course you can set it to whatever you want
- Print widget information, including slug title and duration. See sample above
- Only download separate audio if exists (some items have video and audio combined)

I should be able to push a commit tomorrow with these changes.

**Comment by Mennaruuk** [comment]
All right chief, I downloaded the video and audio successfully. Works great!

**Comment by 89z** [comment]
Should work with other shows too, here is list

https://github.com/89z/mech/tree/master/pbs

**Comment by 89z** [comment]
OK I pushed a new commit with those changes. Also, I am thinking about adding sorting for height, but I am not sure yet.
