### ISSUE TITLE
[Bandcamp] Specify format to download (mp3, etc)?

### ISSUE THREAD

**Issue by 7k50** [89z/mech#42]
Is there a way to specify which format to download files in?

When trying the Bandcamp module, it seems like the format I get is .m2a files. Would love to be able to specify .mp3 for example.

I could not find anything about this in the documentation – so if it is not possible, It'd be a good feature request.

**Comment by 89z** [comment]
please provide example URL

**Comment by 7k50** [comment]
> please provide example URL

`./bandcamp -a https://velenoviola.bandcamp.com/track/ospedale-psichiatrico-infantile-di-ferrara-where-the-story-begins`

Creates: `Veleno Viola-Ospedale Psichiatrico Infantile Di Ferrara (Where The Story Begins).m2a`

**Comment by 89z** [comment]
I think I can fix this. Looks like these should all be options:

~~~
[.mp2 .mp3 .mpa]
~~~

I can set `.mp3` as the default, and add a flag to override.

**Comment by 89z** [comment]
OK this should be fixed now. Also I fixed an issue with albums, where every track was getting the same name. Any problems let me know
