### ISSUE TITLE
[twitter] Try to download mp3

### ISSUE THREAD

**Issue by 454478978** [89z/mech#44]
Hi, I'm trying to download the recorded audio from twitter space, but met some problems
`C:\Users\45447\mech\twitter>go run . -c 1lPKqmwmOWbKb
package github.com/89z/mech/twitter is not a main package`
I'm stuck in here, in order to get the downloaded file, what should I do next?

**Comment by 89z** [comment]
I removed Twitter Space because it was annoying to support. The last version is here:

https://github.com/89z/mech/tree/v1.50.2

If you are willing to make a donation, I can restore it to the current version. Otherwise you will need to use the old version.

**Comment by 89z** [comment]
I fixed the Twitter search, so I might be able to restore this

**Comment by 89z** [comment]
This should be fixed now:

https://github.com/89z/mech/tree/v1.51.4
