### ISSUE TITLE
[tiktok] can't download the video, it shows it's forbidden

### ISSUE THREAD

**Issue by 89z** [89z/mech#56]
https://www.tiktok.com/@hankgreen1/video/7071004694751071494

https://www.tiktok.com/@hankgreen1/video/7075881489216392453

`github.com/TufayelLUS/TikTok-Video-Downloader-PHP/issues/40`

**Comment by 89z** [comment]
Fixed:

~~~
PS D:\Desktop> tiktok -b 7071004694751071494
GET http://api2.musical.ly/aweme/v1/aweme/detail/?aweme_id=7071004694751071494
GET https://v16m-default.akamaized.net/58e716bc5b829b904de93cffea6d3068/625f49df/video/tos/useast2a/tos-useast2a-ve-0068c001/34538042a77e4ecc8fe562874864787a/?a=0&br=4102&bt=2051&cd=0%7C0%7C0%7C0&ch=0&cr=0&cs=0&cv=1&dr=0&ds=6&er=&ft=rkAEY0BN1rfvjwWA9kvNTusGvNXXySY1G~eBCTh&l=202204191746190102230981511D5069B9&lr=all&mime_type=video_mp4&net=0&pl=0&qs=0&rc=anU1ajQ6ZnduOzMzNzczM0ApOTo2OzVoO2UzNzc5PDc8ZGdrZWBhcjRnLWRgLS1kMTZzcy8vNGM0MTYvNDVgNDM1MzY6Yw%3D%3D&vl=&vr=

PS D:\Desktop> tiktok -b 7075881489216392453
GET http://api2.musical.ly/aweme/v1/aweme/detail/?aweme_id=7075881489216392453
GET https://v16m-default.akamaized.net/90952438aacf97c8f1da35840ee04e07/625f4a00/video/tos/useast2a/tos-useast2a-pve-0068/4982104490614131a2cc218f2e29f5d1/?a=0&br=3014&bt=1507&cd=0%7C0%7C0%7C0&ch=0&cr=0&cs=0&cv=1&dr=0&ds=6&er=&ft=rkAEY0BN1rfvjwWA9kvNTusxvNXXySY1G~eBCTh&l=202204191746220102230981511D506C89&lr=all&mime_type=video_mp4&net=0&pl=0&qs=0&rc=M2R1Nmk6Zjc8OzMzNzczM0ApNmg5M2k7OzxlNztnZTVoOGdqa2tscjRfM21gLS1kMTZzc2AyYzNjLi5iMjZiYy4wMy86Yw%3D%3D&vl=&vr=
~~~

**Comment by 89z** [comment]
https://github.com/TufayelLUS/TikTok-Video-Downloader-PHP/issues/40

**Comment by 89z** [comment]
@hassanfaizm  @pedrosaartes

**Comment by ajt1923** [comment]
Can you explain where to put this code?

PS D:\Desktop> tiktok -b 7071004694751071494
GET http://api2.musical.ly/aweme/v1/aweme/detail/?aweme_id=7071004694751071494
GET https://v16m-default.akamaized.net/58e716bc5b829b904de93cffea6d3068/625f49df/video/tos/useast2a/tos-useast2a-ve-0068c001/34538042a77e4ecc8fe562874864787a/?a=0&br=4102&bt=2051&cd=0%7C0%7C0%7C0&ch=0&cr=0&cs=0&cv=1&dr=0&ds=6&er=&ft=rkAEY0BN1rfvjwWA9kvNTusGvNXXySY1G~eBCTh&l=202204191746190102230981511D5069B9&lr=all&mime_type=video_mp4&net=0&pl=0&qs=0&rc=anU1ajQ6ZnduOzMzNzczM0ApOTo2OzVoO2UzNzc5PDc8ZGdrZWBhcjRnLWRgLS1kMTZzcy8vNGM0MTYvNDVgNDM1MzY6Yw%3D%3D&vl=&vr=

PS D:\Desktop> tiktok -b 7075881489216392453
GET http://api2.musical.ly/aweme/v1/aweme/detail/?aweme_id=7075881489216392453
GET https://v16m-default.akamaized.net/90952438aacf97c8f1da35840ee04e07/625f4a00/video/tos/useast2a/tos-useast2a-pve-0068/4982104490614131a2cc218f2e29f5d1/?a=0&br=3014&bt=1507&cd=0%7C0%7C0%7C0&ch=0&cr=0&cs=0&cv=1&dr=0&ds=6&er=&ft=rkAEY0BN1rfvjwWA9kvNTusxvNXXySY1G~eBCTh&l=202204191746220102230981511D506C89&lr=all&mime_type=video_mp4&net=0&pl=0&qs=0&rc=M2R1Nmk6Zjc8OzMzNzczM0ApNmg5M2k7OzxlNztnZTVoOGdqa2tscjRfM21gLS1kMTZzc2AyYzNjLi5iMjZiYy4wMy86Yw%3D%3D&vl=&vr=

**Comment by 89z** [comment]
https://github.com/89z/mech#money
