### ISSUE TITLE
LOGIN_REQUIRED This video may be inappropriate for some users.

### ISSUE THREAD

**Issue by ole-tange** [89z/mech#6]
https://github.com/ytdl-org/youtube-dl/issues/30019#issuecomment-927149735 refers to this program.

However, it fails:

~~~
$ youtube E577jhf25t4

POST /youtubei/v1/player HTTP/1.1
Host: www.youtube.com
X-Goog-Api-Key: Axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx8

{"context":{"client":{"clientName":"ANDROID","clientVersion":"16.05"}},"videoId":"E577jhf25t4"}
LOGIN_REQUIRED This video may be inappropriate for some users.
~~~

**Comment by 89z** [comment]
Try this instead:

~~~
youtube -e E577jhf25t4
~~~

Closing this. If error continues, let me know. Thanks!

**Comment by 89z** [comment]
Looks like on Unix, the info is pulled from here:

<https://github.com/golang/go/blob/go1.17.2/src/mime/type_unix.go#L20-L33>

can you clarify what distribution you are on? I would like to avoid hard coding the extensions, but I might not have a choice. In the meantime I will try a few from here:

https://distrowatch.com
