### ISSUE TITLE
[Paramount] quality issues 

### ISSUE THREAD

**Issue by 89z** [89z/mech#74]
https://www.paramountplus.com/shows/video/W1DNS7lqDp0TkZnxAfcM0bsJYhxtuT_x/

`github.com/yt-dlp/yt-dlp/issues/3833`

**Comment by 89z** [comment]
Fixed:

~~~
> paramount -b W1DNS7lqDp0TkZnxAfcM0bsJYhxtuT_x -i -d
GET http://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/W1DNS7lqDp0TkZnxAfcM0bsJYhxtuT_x?format=preview
HEAD http://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/W1DNS7lqDp0TkZnxAfcM0bsJYhxtuT_x?assetTypes=DASH_CENC&formats=MPEG-DASH
GET https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2014/09/23/332430915783/846210_cenc_dash/stream.mpd
!ID:7 Bandwidth:131101 Codec:mp4a.40.2
ID:5 Bandwidth:194323 Codec:ec-3
ID:6 Bandwidth:386323 Codec:ac-3
ID:15 Width:640 Height:360 Bandwidth:491328 Codec:avc1.640028
ID:13 Width:768 Height:432 Bandwidth:988020 Codec:avc1.640028
!ID:12 Width:960 Height:540 Bandwidth:1963296 Codec:avc1.640028
ID:11 Width:1024 Height:576 Bandwidth:2741707 Codec:avc1.640028
ID:10 Width:1280 Height:720 Bandwidth:3938438 Codec:avc1.640028
ID:14 Width:1920 Height:1080 Bandwidth:5795853 Codec:avc1.640028

> paramount -b W1DNS7lqDp0TkZnxAfcM0bsJYhxtuT_x -d
GET http://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/W1DNS7lqDp0TkZnxAfcM0bsJYhxtuT_x?format=preview
HEAD http://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/W1DNS7lqDp0TkZnxAfcM0bsJYhxtuT_x?assetTypes=DASH_CENC&formats=MPEG-DASH
GET https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2014/09/23/332430915783/846210_cenc_dash/stream.mpd
GET https://www.paramountplus.com/apps-api/v3.0/androidphone/irdeto-control/anonymous-session-token.json?at=ABAAAAAAAAAAAAAAAAAAAAAAllAdZ6mDhF74gwOlMlndMKU5zcd9%2B2A8QGEmkmwlJjE%3D
POST https://cbsi.live.ott.irdeto.com/widevine/getlicense?CrmId=cbsi&AccountId=cbsi&SubContentType=Default&contentId=W1DNS7lqDp0TkZnxAfcM0bsJYhxtuT_x
GET https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2014/09/23/332430915783/846210_cenc_dash/CBS_NCIS_259_HD_en-US_466810_3_aac_128/init.m4v
5.3%    2.275 MB        4.436 MB/s
~~~

**Comment by wxolp** [comment]
https://github.com/yt-dlp/yt-dlp/issues/3833

**Comment by 89z** [comment]
@BrendanoElTaco

**Comment by BrendanoElTaco** [comment]
What exactly am I supposed to do with this repo? I'm on windows btw

**Comment by 89z** [comment]
> What exactly am I supposed to do with this repo?

If youre interested, you can use the Paramount tool to download from Paramount, as I showed above.

> I'm on windows btw

My tools work with Windows, macOS and Linux. You can build yourself, or I have a build here:

https://github.com/89z/mech/releases/tag/v1.53.5

**Comment by BrendanoElTaco** [comment]
When I try to run: paramount -b W1DNS7lqDp0TkZnxAfcM0bsJYhxtuT_x -d I get 

panic: open C:\Users\Brendan\mech\private_key.pem: The system cannot find the path specified.

goroutine 1 [running]:
main.main()
        github.com/89z/mech/cmd/paramount/main.go:66 +0x585

**Comment by 89z** [comment]
That file contains the RSA private key needed for decrypting. I cant host it here for legal reasons, but you should be able to download it from here:

<https://github.com/Jnzzi/4464_L3-CDM>

or you can dump your own:

https://github.com/89z/mech/tree/v1.53.9/widevine#how-to-dump-l3-cdm

Note that if you choose to download the files from the link above, you need to either rename the files to match the defaults, or you can manually set the paths like this:

~~~
-c string
     client ID (default "C:\\Users\\Steven\\mech\\client_id.bin")
-k string
     private key (default "C:\\Users\\Steven\\mech\\private_key.pem")
~~~

**Comment by BrendanoElTaco** [comment]
I believe I got it working. Thank you so much for the help and the amazing program!

**Comment by 89z** [comment]
please star this repo, if its helpful

**Comment by BrendanoElTaco** [comment]
Done!
