### ISSUE TITLE
[BBC America] Unable to download JSON 

### ISSUE THREAD

**Issue by 89z** [89z/mech#78]
https://www.bbcamerica.com/shows/almost-royal/episodes/season-2-beauty--1010702

`github.com/yt-dlp/yt-dlp/issues/3984`

**Comment by 89z** [comment]
Fixed:

~~~
> amc -b 1010702
POST https://gw.cds.amcn.com/auth-orchestration-id/api/v1/refresh
Create C:\Users\Steven\mech\amc.json
POST https://gw.cds.amcn.com/playback-id/api/v1/playback/1010702
GET http://ssaimanifest.prod.boltdns.net/playback/once/v1/dash/live-timeline/bccenc/6245817279001/74263065-1285-4d00-842d-73a66554716a/637ceb43-7ae1-4052-b148-e200c81a88f2/manifest.mpd?bc_token=NjJhMjliYTZfMDVmNGZjYjNlOGZmZjAwYzc5YmJjMGU4MjI3NDUwMTUzZTRmYTk2MThmZWRiMjQ2ZTdmMWYxMTFlZWU3MGU1NA%3D%3D
GET http://redirector.playback.us-east-1.prod.deploys.brightcove.com/v1/6245817279001/2fd7dc7e-2432-4cf2-a15b-a44cc416b12d/xd4/default_audio128_5_en_main/init0.m4f
POST https://manifest.prod.boltdns.net/license/v1/cenc/widevine/6245817279001/637ceb43-7ae1-4052-b148-e200c81a88f2/eb6c9c41-3f7b-4d14-90cb-4d1611a7cd8e?fastly_token=NjJhMjliYTZfNmQ2ZjVlMjFkYTkyZmY4NTNmN2RmODdjODcyYzA3YmVmNmEzMTkzZTAzZjFlYTVmNjY5M2U0NmI5YTU4MDEzYQ%3D%3D
4.6%    1.002 MB        993.122 kB/s
~~~

**Comment by wxolp** [comment]
https://github.com/yt-dlp/yt-dlp/issues/3984

**Comment by 89z** [comment]
@teo4all

**Comment by teo4all** [comment]
What am I doing wrong? 

`amc -b 1010702
panic: open C:\Users\Teo\mech\amc.json: The system cannot find the file specified.

goroutine 1 [running]:
main.main()
        R:/Captures/PlayOn/mech-master/cmd/amc/main.go:59 +0x5f0`

**Comment by teo4all** [comment]
I am loging in the amc site with tv provider (DirecTV) credentials, and when I try them i get this
```
`POST https://gw.cds.amcn.com/auth-orchestration-id/api/v1/unauth
POST https://gw.cds.amcn.com/auth-orchestration-id/api/v1/login
panic: 401 Unauthorized

goroutine 1 [running]:
main.main()
        R:/Captures/PlayOn/mech-master/cmd/amc/main.go:54 +0x5e5`
```

**Comment by 89z** [comment]
My tool works with AMC+ account. If you are willing to share credentials, I can try to add support for DirecTV login.

**Comment by 89z** [comment]
https://github.com/89z/format/issues/5

**Comment by 89z** [comment]
This should be fixed now. If you still have trouble let me know

https://github.com/89z/mech/blob/348ab712e12ae2f1807e2e75cbe142a172016238/cmd/amc/amc.go#L125-L127

**Comment by dano-code** [comment]
@teo4all - How did you get it working with a TV Provider? I have a login linked to my TV provider, but getting unauthorized when trying to sign in.
