### ISSUE TITLE
How to get decryption key?

### ISSUE THREAD

**Issue by 89z** [89z/mech#79]
~~~
ffmpeg -cenc_decryption_key 66363435386631333730396636386565 `
-i http://vrbx507.cda.pl/3916348/3916348.mpd `
-c copy -map 0:0 dec.mp4
~~~

`github.com/ytdl-org/youtube-dl/issues/30873`

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30873

**Comment by 89z** [comment]
@gucio321 we can talk here if you want

**Comment by gucio321** [comment]
well, so, how do you get this hash code? I'm not familiar with web APIs

**Comment by 89z** [comment]
I added a new command:

https://github.com/89z/mech/tree/master/cmd/widevine

example:

~~~
widevine `
-b 63363432-3534-6364-6237-656465336530 `
-a https://lic.drmtoday.com/license-proxy-widevine/cenc/?specConform=true `
-h x-dt-custom-data:eyJ1c2VySWQiOiJhbm9uaW0iLCJzZXNzaW9uSWQiOiJrRGJZZUlYeVM4VjNtNXVRMjRtU0F6cThXdDkiLCJtZXJjaGFudCI6ImNkYSJ9
~~~

output:

~~~
POST https://lic.drmtoday.com/license-proxy-widevine/cenc/?specConform=true
66363435386631333730396636386565
~~~

**Comment by gucio321** [comment]
Oh i see that you have great stuff. Cute could you explain me what these parameters are and how to get them

**Comment by 89z** [comment]
I added some brief information here:

https://github.com/89z/mech/tree/master/cmd/widevine

**Comment by gucio321** [comment]
well, I got all necessary numbers but now i don't know how to use widevine.go...
I'm executing
```console
./widevine -b <default kID> -a <license url> -h <x-dt-custom-data>
```
and the app panics with
```console
panic: open /home/me/mech/client_id.bin: no such file or directory
```
I'm pretty sure that I'm missing -c option however idk what should it be

**Comment by 89z** [comment]
I added some more information:

https://github.com/89z/mech/tree/master/cmd/widevine#how-to-get-client-id-and-private-key-files

**Comment by gucio321** [comment]
cool, thank you!
One more question, what to do with this number I got from widevine?

**Comment by 89z** [comment]
If you get a result like this:

~~~
66363435386631333730396636386565
~~~

then you can download like this:

~~~
ffmpeg -cenc_decryption_key 66363435386631333730396636386565 `
-i http://vrbx507.cda.pl/3916348/3916348.mpd `
-c copy -map 0:0 dec.mp4
~~~

**Comment by iamDonkey** [comment]
this method is same for all websites that has drm protected content?

**Comment by 89z** [comment]
Some websites like Apple TV+, wrap the license request body in JSON, so my Widevine tool would not work. However I am trying to make a custom tool for Apple TV+. If you find some site that is not working, let me know

**Comment by gucio321** [comment]
```console
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Unrecognized option 'cenc_decryption_key'.
Error splitting the argument list: Option not found
```
ffmpeg refuses to find cenc_decryption_key option...

**Comment by 89z** [comment]
This option is only available with FFmpeg builds since 2022-05-16

**Comment by 89z** [comment]
I could make a tool to download and decrypt MPD, but I am busy with other tasks. If you wish to make a donation, I can work on it right away. Otherwise good luck
