### ISSUE TITLE
Bandcamp and soundcloud build no output file (OS X)

### ISSUE THREAD

**Issue by yakuv0** [89z/mech#87]
Hello

tried to build soundcloud and bandcamp with go and got no output file on a mac Mojave, go v1.18.3
Builds succeeds in cmds folder

edit:
error after building with `go build -o bandcamp` Then giving it execute permission, received on execution 

```
line 1: syntax error near unexpected token `newline'
line 1: `!<arch>'
```
Edit:
Same build issue on windows 7

cheers

**Comment by yakuv0** [comment]
> https://github.com/89z/mech#issues

Hello, 
already proceeded with the suggestion and posted the errors, the `go build` Works for the services in cmd folder but not bandcamp or soundcloud.

Cheers

**Comment by 89z** [comment]
I think you did not read the link:

> During this time I am trying to support myself, so I am requiring payment for all issues. That might change at a later date. Any issue without payment of at least 9 USD will be closed immediately. Payment can be made to the PayPal link on this page, or if you need to use another method, mention that in the issue text. For business opportunities, contact me:

**Comment by yakuv0** [comment]
Thanks for replying but the link just takes to the main repo, and there’s no info there on build and installation other than navigating to the directory and running `go build`, and same issue happens on windows and mac OS X.
Really appreciate it
