### ISSUE TITLE
[Reddit] Add support for 1080p videos

### ISSUE THREAD

**Issue by jeevatattva** [89z/mech#9]
>Basically, the problem is that Reddit does not provide all formats when requesting with the base DASH and HLS playlist urls (e.g., https://v.redd.it/33hgok7dfbz71/DASHPlaylist.mpd). To fix this, certain query parameters must be attached to it, which must be obtained from the video page itself. Although this requires an additional request, it is well-justified as now one can download 1080p videos (i.e., highest quality)

https://github.com/yt-dlp/yt-dlp/pull/1682

**Comment by 89z** [comment]
https://redd.it/qsw48i

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29565

**Comment by jeevatattva** [comment]
```sh
$ reddit -df qsw48i
GET /by_id/t3_qsw48i HTTP/1.1
Host: api.reddit.com
User-Agent: Mozilla

GET /33hgok7dfbz71/DASHPlaylist.mpd HTTP/1.1
Host: v.redd.it

{ID:audio_0_5700 MimeType:audio/mp4 BaseURL:https://v.redd.it/33hgok7dfbz71/DASH_audio.mp4}
{ID:video_572845 MimeType:video/mp4 BaseURL:https://v.redd.it/33hgok7dfbz71/DASH_240.mp4}
{ID:video_756288 MimeType:video/mp4 BaseURL:https://v.redd.it/33hgok7dfbz71/DASH_360.mp4}
{ID:video_1121942 MimeType:video/mp4 BaseURL:https://v.redd.it/33hgok7dfbz71/DASH_480.mp4}
{ID:video_2186728 MimeType:video/mp4 BaseURL:https://v.redd.it/33hgok7dfbz71/DASH_720.mp4}

$ reddit -hf qsw48i
GET /by_id/t3_qsw48i HTTP/1.1
Host: api.reddit.com
User-Agent: Mozilla

GET /33hgok7dfbz71/HLSPlaylist.m3u8 HTTP/1.1
Host: v.redd.it

{ID:0 Resolution: URI:https://v.redd.it/33hgok7dfbz71/HLS_AUDIO_160_K.m3u8}
{ID:1 Resolution: URI:https://v.redd.it/33hgok7dfbz71/HLS_AUDIO_64_K.m3u8}
{ID:2 Resolution:1024x576 URI:https://v.redd.it/33hgok7dfbz71/HLS_576-iframe.m3u8}
{ID:3 Resolution:1024x576 URI:https://v.redd.it/33hgok7dfbz71/HLS_576.m3u8}
{ID:4 Resolution:400x226 URI:https://v.redd.it/33hgok7dfbz71/HLS_224-iframe.m3u8}
{ID:5 Resolution:400x226 URI:https://v.redd.it/33hgok7dfbz71/HLS_224.m3u8}
{ID:6 Resolution:480x270 URI:https://v.redd.it/33hgok7dfbz71/HLS_270-iframe.m3u8}
{ID:7 Resolution:480x270 URI:https://v.redd.it/33hgok7dfbz71/HLS_270.m3u8}
{ID:8 Resolution:640x360 URI:https://v.redd.it/33hgok7dfbz71/HLS_360-iframe.m3u8}
{ID:9 Resolution:640x360 URI:https://v.redd.it/33hgok7dfbz71/HLS_360.m3u8}
{ID:10 Resolution:960x540 URI:https://v.redd.it/33hgok7dfbz71/HLS_540-iframe.m3u8}
{ID:11 Resolution:960x540 URI:https://v.redd.it/33hgok7dfbz71/HLS_540.m3u8}
```

`1080p` is not listed even where the resource URL has `DASH_1080.mp4`.

**Comment by 89z** [comment]
This should be fixed now. Let me know if you have any other problems, thanks!

**Comment by jeevatattva** [comment]
Thank you for the quick response, and also, instantly providing a fix. Querying `id` `qsw48i` does show `1080p` now, but for other links, the maximum resolution is limited to`720p`, when in fact I see `1080p` on my computer, e.g. `id` `r07ewc`.

**Comment by 89z** [comment]
Visiting that page in browser, I only see option for 720

https://www.reddit.com/r/cyberpunkgame/comments/r07ewc

I am going to close this again. If you can help me to see how to get 1080p in browser, then I will open again

**Comment by 89z** [comment]
I am going to reopen this (for now). I will check the Reddit APK to see if its doing anything different.

**Comment by 89z** [comment]
OK sorry, but I checked the same post with APK as well, only saw 720. So unless you can give something more, going to keep this closed. Thanks!
